import Head from 'next/head';
import { onAuthStateChanged } from 'firebase/auth';
import { auth } from "../firebase";
import { useState } from "react";
import Navbar from '../components/Navbar';
import GameContainer from '../components/GameContainer';
import CoinBtn from '../components/CoinBtn';


export default function Home() {
  
  
  const [username, setUsername] = useState("");
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  onAuthStateChanged(auth, (user:any) => {
    if (user) {
      setIsLoggedIn(true);
      setUsername(user.email.substring(0, user.email.indexOf("@")));
      
    } else {
      setIsLoggedIn(false);
    }
  })  



  



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col justify-center items-center'>
        <Navbar />
        {isLoggedIn && <p>Hi {username}!</p>}
        <CoinBtn />
        <div className='w-[85vw] h-[85vh] flex justify-center items-center'>
          <GameContainer />
          
        </div>
      </div>
    </>
    
  )
}
